#---------------------------------------------------#
## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效
#---------------------------------------------------#

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: false

# 规则模式：Global（全局代理）/ Rule（规则） / Script(腳本) / Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# clash 的 RESTful API
external-controller: '0.0.0.0:9090'


# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `${API}/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

# RESTful API 的口令 (可选)
secret: ""

# DNS 设置

dns:
 enable: true
 ipv6: false
 listen: 0.0.0.0:53
 enhanced-mode: redir-host
 nameserver:
  - 8.8.8.8
  - 119.29.29.29
  - 223.5.5.5
  - https://rubyfish.cn/dns-query
 fallback:
  - https://cloudflare-dns.com/dns-query
  - tls://1.0.0.1:853
  - https://dns.google/dns-query#

# 代理节点
proxy-providers:

  Airport:
    type: http
    path: ./Server/Sub.yaml # 这里文件名称需要与订阅节点名称一样
    url: # 这里填写订阅链接
    interval: 3600
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300
# 香港
  Hong Kong:
    type: file
    path: ./Server/Sub.yaml
    filter: '香港'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 3600
  # 台湾
  Taiwan:
    type: file
    path: ./Server/Sub.yaml
    filter: '台湾'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 3600
  # 日本
  Japan:
    type: file
    path: ./Server/Sub.yaml
    filter: '日本'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 3600
  # 韩国
  Korea:
    type: file
    path: ./Server/Sub.yaml
    filter: '韩国'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 3600
  # 新加坡
  Singapore:
    type: file
    path: ./Server/Sub.yaml
    filter: '新加坡|狮城'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 3600
  # 美国
  United States:
    type: file
    path: ./Server/Sub.yaml
    filter: '美国'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 3600
  # 英国
  United Kingdom:
    type: file
    path: ./Server/Sub.yaml
    filter: '英国'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 3600
# 代理组策略
proxy-groups:

# 策略组说明

# 「Proxy」是代理规则策略，它可以指定为某个节点或嵌套一个其他策略组，如：「url-test」（自动测试）、「Fallback」或「load-balance」（负载均衡）的策略组

  - { name: "MATCH", type: select, proxies: ["Proxy"]} 
  - { name: "Dler", type: select, use: ["Hong Kong","United States","Dler Cloud"]} 
  - { name: "Microsoft", type: select, proxies: ["DIRECT"], use: ["United States"]}  
  - { name: "Apple", type: select, proxies: ["DIRECT"], use: ["United States","Japan"]}
  - { name: "Adobe", type: url-test, use: ["United States"]}
  - { name: "paypal", type: url-test, use: ["United States"]}
  - { name: "Amazon", type: url-test, use: ["United States"]}
  - { name: "Google", type: url-test, use: ["United States"]}
  - { name: "YouTube", type: url-test, use: ["United States"]}
  - { name: "Telegram", type: url-test, use: ["Hong Kong"]}
  - { name: "Twitter", type: url-test, use: ["Hong Kong"]}
  - { name: "Facebook", type: url-test, use: ["Hong Kong"]}
  - { name: "GitHub", type: url-test, use: ["Hong Kong"]}
  - { name: "Proxy", type: url-test, use: ["Hong Kong","United States"]} 



# 分流规则  
rules:
  - RULE-SET,AdBlock,REJECT
  - RULE-SET,Proxy,Proxy
  - RULE-SET,Apple,Apple
  - RULE-SET,Adobe,Adobe
  - RULE-SET,Amazon,Amazon
  - RULE-SET,Dler,Dler
  - RULE-SET,Facebook,Facebook 
  - RULE-SET,GitHub,GitHub
  - RULE-SET,Google,Google
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Netflix,Netflix 
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,Steam,Steam
  - RULE-SET,Spotify,Spotify
  - RULE-SET,Telegram,Telegram 
  - RULE-SET,Twitter,Twitter 
  - RULE-SET,Tencent,Tencent
  - RULE-SET,TencentVideo,TencentVideo
  - RULE-SET,YouTube,YouTube 
  - RULE-SET,PayPal,paypal
  - RULE-SET,Discord,Discord
  - DOMAIN-SUFFIX,live.cn,China
  # (Dler)
  - DOMAIN-SUFFIX,sub.dler.io,Dler
  - DOMAIN-SUFFIX,api.suo.yt,Dler
  - DOMAIN-SUFFIX,dlercloud.com,Dler
  - DOMAIN-KEYWORD,dlercloud,Dler

  - GEOIP,CN,DIRECT
  - MATCH,MATCH

rule-providers:

  AdBlock: {type: http, behavior: classical, path: ./Filter/AdBlock, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/AdBlock.yaml, interval: 3600}
  Apple: {type: http, behavior: classical, path: ./Filter/Apple, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Apple.yaml, interval: 3600}
  Adobe: {type: http, behavior: classical, path: ./Filter/Adobe, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Adobe.yaml, interval: 3600}
  Amazon: {type: http, behavior: classical, path: ./Filter/Amazon, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Amazon.yaml, interval: 3600}

  China: {type: http, behavior: classical, path: ./Filter/China, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/China.yaml, interval: 3600}

  Dler: {type: http, behavior: classical, path: ./Filter/Dler, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Dler.yaml, interval: 3600}

  Facebook: {type: http, behavior: classical, path: ./Filter/Facebook, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Facebook.yaml, interval: 3600}

  GitHub: {type: http, behavior: classical, path: ./Filter/GitHub, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/GitHub.yaml, interval: 3600}
  Google: {type: http, behavior: classical, path: ./Filter/Google, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Google.yaml, interval: 3600}
  
  Microsoft: {type: http, behavior: classical, path: ./Filter/Microsoft, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Microsoft.yaml, interval: 3600}
  
  Netflix: {type: http, behavior: classical, path: ./Filter/Netflix, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Netflix.yaml, interval: 3600}
  
  Spotify: {type: http, behavior: classical, path: ./Filter/Spotify, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Spotify.yaml, interval: 3600}
  Speedtest: {type: http, behavior: classical, path: ./Filter/Speedtest, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Speedtest.yaml, interval: 3600}
  Steam: {type: http, behavior: classical, path: ./Filter/Steam, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Steam.yaml, interval: 3600}

  Telegram: {type: http, behavior: classical, path: ./Filter/Telegram, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Telegram.yaml, interval: 3600}
  Twitter: {type: http, behavior: classical, path: ./Filter/Twitter, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Twitter.yaml, interval: 3600}
  Tencent: {type: http, behavior: classical, path: ./Filter/Tencent, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Tencent.yaml, interval: 3600}
  TencentVideo: {type: http, behavior: classical, path: ./Filter/TencentVideo, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/TencentVideo.yaml, interval: 3600}

  YouTube: {type: http, behavior: classical, path: ./Filter/YouTube, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/YouTube.yaml, interval: 3600}

  PayPal: {type: http, behavior: classical, path: ./Filter/PayPal, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/PayPal.yaml, interval: 3600}
  Discord: {type: http, behavior: classical, path: ./Filter/Discord, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Discord.yaml, interval: 3600}
  Proxy: {type: http, behavior: classical, path: ./Filter/Proxy, url: https://raw.githubusercontent.com/Semporia/Clash/master/Rule/Proxy.yaml, interval: 3600}

